(() => {
  const slug = location.pathname.split('/').filter(Boolean).at(-2);
  const page = location.pathname.split('/').pop().replace('.html','');
  const data = {
    'carolina-beer-temple':{name:'Carolina Beer Temple',kind:'beer discovery',accent:'#4b7622',pages:{menu:['Tap list','A useful, current-first way to see what is pouring.','Browse the live tap list before you visit; availability changes.'],story:['Why the Temple','A craft beer bar and retail store in downtown Matthews.','The point is discovery, not homework.'],experience:['Discovery route','Choose a familiar style or ask for a direction.','The best flight is the one that helps you find a new favorite.'],reserve:['Plan your stop','Choose a visit plan for the Temple.','This concept does not submit an order or reservation.'],visit:['Visit in Matthews','195 N Trade St, Matthews, NC 28105.','Use the official site to confirm current hours and events.']}},
    'sir-edmond-halleys':{name:"Sir Edmond Halley's",kind:'Park Road neighborhood pub',accent:'#b58a41',pages:{menu:['The pub menu','Burgers, fish and chips, shepherd’s pie, curries, and the comfort food that makes a pub a regular stop.','Use Sir Ed’s official menu for current details and pricing.'],story:['The local pub','In the back of Park Road Shopping Center, Sir Ed’s has been part of Madison Park since 1996.','The point is an easy welcome and a long conversation.'],experience:['The Half Yard','A memorable beer ritual deserves a clearer explanation and practical guidance.','Ask the pub for current availability.'],reserve:['Plan your visit','Start with the right time, the right table, and the current pub details.','This concept does not submit a reservation.'],visit:['Find Sir Ed’s','4151 A Park Rd, Charlotte, NC 28209.','Call (704) 525-7775 for current hours and details.']}}
    'dbs-tavern':{name:"DB's Tavern",kind:'Ballantyne tavern',accent:'#f26b38',pages:{menu:['Menu for the table','Wings, pizza rolls, burgers, and tavern food.','Visit DBâ€™s official menu for live offerings and prices.'],story:['The neighborhood room','A Ballantyne tavern built for food, drinks, and game day.','Some nights are a barstool; some are a full table.'],experience:['Wings & game day','Pick your heat, get the game on, settle in.','Use the current menu for live choices.'],reserve:['Order takeout','A clearer takeout path starts with the live menu.','This concept is not an ordering system.'],visit:['Find DBâ€™s','8155 Ardrey Kell Rd, Charlotte, NC 28277.','Call (704) 844-0534 for current details.']}},
    'mckoys-smokehouse-and-saloon':{name:"McKoy's Smokehouse & Saloon",kind:'smokehouse',accent:'#a8492d',pages:{menu:['From the pit','Pulled pork, smoked ribs, pot roast, wings, and sides.','Check the official menu for current items and pricing.'],story:['The McKoyâ€™s way','Family recipes, a patient pit, and a saloon where people stay awhile.','Comfort carries the story.'],experience:['Groups & gatherings','Bring the table together around smokehouse food.','Contact the restaurant for current group options.'],reserve:['Plan a group visit','Start a simple group-planning preview.','This concept does not send an inquiry.'],visit:['Find McKoyâ€™s','4630 Old Pineville Rd, Charlotte, NC 28217.','Call the restaurant for current service details.']}},
    'barringtons-restaurant':{name:"Barrington's",kind:'Charlotte dining room',accent:'#7b3931',pages:{menu:['The menu','A considered meal deserves a menu that reads with ease.','Use Barringtonâ€™s official channels for current courses and prices.'],story:['The room','Contemporary American cooking and an evening with intention.','The pace is part of the experience.'],experience:['The evening','A practical guide to planning a dinner that feels unhurried.','Confirm current availability before you go.'],reserve:['Plan a table','Choose a party size and timing for a demo-only plan.','No reservation is created here.'],visit:['Visit Barringtonâ€™s','Charlotte, North Carolina.','Use the official site for current address, hours, and reservations.']}},
    'duckworths-grill-taphouse':{name:"Duckworth's",kind:'grill & taphouse',accent:'#e95032',pages:{menu:['Food for the table','Grill favorites, wings, burgers, pizza, and beer.','Use the official menu for current items and pricing.'],story:['The taphouse','A locally owned grill and taphouse with multiple North Carolina locations.','Choose the room that works for your day.'],experience:['Beer & game day','Find a taphouse, a current tap, and a reason to settle in.','Availability varies by location.'],reserve:['Choose your location','Start with the location, then confirm current reservations.','This is a planning preview only.'],visit:['Locations','Charlotte, Huntersville, Mooresville, and more.','Use Duckworthâ€™s official location page for live hours.']}},
    'hopfly-brewing':{name:'HopFly Brewing',kind:'Gold District taproom',accent:'#8cbd35',pages:{menu:['Whatâ€™s pouring','IPAs, lagers, and experimental releases in a living taproom.','Use HopFlyâ€™s official channels for live availability.'],story:['The Gold District room','A Charlotte taproom opened in 2022 to grow with its creative community.','Walk through the patio and stay awhile.'],experience:['The loft & patio','Rooftop views, a dog-friendly patio, food trucks, and room to gather.','Check the official schedule for events.'],reserve:['Plan a gathering','A simple group-planning starting point.','This concept does not submit an event request.'],visit:['Visit HopFly','1327 S Mint St, Charlotte, NC 28203.','Confirm current taproom hours on HopFlyâ€™s official site.']}},
    'idlewild':{name:'Idlewild',kind:'NoDa cocktail bar',accent:'#c3843e',pages:{menu:['No printed menu','Tell the bartender a flavor, feeling, spirit, or memory.','The conversation is the menu.'],story:['A little cocktail bar','Idlewild is built around bartender-led drinks, not a fixed list.','Walk-ins welcome; practical limits matter.'],experience:['Find your drink','Choose a mood and give the bartender a starting point.','The result is a concept preview, not an order.'],reserve:['Before you go','Walk-ins welcome; no children; parties over six are not accommodated.','Confirm the current policy on the official site.'],visit:['Visit Idlewild','424 E 36th Street, Charlotte, NC 28205.','Hours: 6pmâ€“1am Sunâ€“Thu; 6pmâ€“2am Friâ€“Sat.']}},
    'lenny-boy-brewing':{name:'Lenny Boy Brewing',kind:'kombucha & beer taproom',accent:'#d85d3d',pages:{menu:['Beverages','Organic kombucha, beer, wild ales, plus more options for the table.','Use the official site for current pours.'],story:['Started with kombucha','Lenny Boy began brewing kombucha in 2011 and grew into a Charlotte gathering place.','Community is part of the pour.'],experience:['Taproom time','A South End taproom made for lingering, with beer and non-beer options.','Check current events and food details before visiting.'],reserve:['Plan your stop','Choose what you are coming for and build a demo visit plan.','No message is sent.'],visit:['Visit Lenny Boy','3000 S Tryon St, Charlotte, NC 28217.','Call (980) 585-1728 for current details.']}}
  };
  const item=data[slug]?.pages[page]; if(!item)return;
  document.title=`${data[slug].name} | ${item[0]}`;
  document.querySelectorAll('.site-header,.site-footer').forEach((node)=>node.remove());
  const main=document.querySelector('main'); if(!main)return;
  const [title,dek,body]=item;
  const nav=[['index','Home'],['menu','Menu'],['story','Story'],['experience','Explore'],['reserve','Plan'],['visit','Visit']].map(([href,label])=>`<a href="${href}.html">${label}</a>`).join('');
  main.innerHTML=`<section class="refresh-hero"><p>${data[slug].kind}</p><h1>${title}</h1><p>${dek}</p></section><section class="refresh-body"><div><h2>${body}</h2><p>This is an independent concept site. Confirm live information with the business before making plans.</p></div><aside><p>Next step</p><a href="visit.html">Practical visit details â†’</a><a href="menu.html">Explore the menu â†’</a></aside></section><section class="refresh-tool"><h2>Make a simple plan</h2><p>Select what matters most; this is a no-send concept preview.</p><div><button type="button">Food or drink</button><button type="button">A group</button><button type="button">First visit</button></div><p class="refresh-result" aria-live="polite">Choose an option to see a suggested next step.</p></section>`;
  const style=document.createElement('style');style.textContent=`.refresh-nav{display:flex;gap:16px;flex-wrap:wrap}.refresh-hero{padding:100px 10vw;background:${data[slug].accent};color:#171717}.refresh-hero p:first-child{text-transform:uppercase;letter-spacing:.13em;font-size:.72rem;font-weight:700}.refresh-hero h1{font:600 clamp(3rem,7vw,7rem)/.9 Georgia,serif;letter-spacing:-.07em;margin:18px 0}.refresh-hero p:last-child{max-width:620px;font-size:1.15rem}.refresh-body{display:grid;grid-template-columns:1fr .55fr;gap:8vw;padding:90px 10vw}.refresh-body h2,.refresh-tool h2{font:600 clamp(2rem,4vw,4rem)/1 Georgia,serif;letter-spacing:-.05em}.refresh-body aside{border-top:2px solid currentColor;padding-top:16px}.refresh-body aside a{display:block;margin:13px 0;font-weight:700}.refresh-tool{margin:0 10vw 80px;padding:38px;background:#191919;color:#f4f0e8}.refresh-tool button{padding:10px;margin:4px;background:transparent;color:inherit;border:1px solid #aaa;cursor:pointer}.refresh-result{min-height:24px}.refresh-header,.refresh-footer{padding:16px 6vw;display:flex;justify-content:space-between;gap:18px;align-items:center;border-bottom:1px solid #ddd}.refresh-footer{background:#171717;color:#f4f0e8;border:0;font-size:.8rem}.refresh-footer a{color:inherit}.refresh-header strong{font:600 1.1rem Georgia,serif}@media(max-width:650px){.refresh-body{grid-template-columns:1fr;padding:65px 8vw}.refresh-tool{margin:0 8vw 60px}.refresh-hero{padding:75px 8vw}}`;document.head.append(style);
  const header=document.createElement('div');header.className='refresh-header';header.innerHTML=`<strong>${data[slug].name}</strong><nav class="refresh-nav">${nav}</nav>`;document.body.prepend(header);const footer=document.createElement('footer');footer.className='refresh-footer';footer.innerHTML=`<span>${data[slug].name} Â· Independent concept by Dark Star Consulting.</span><a href="../../index.html">Back to showcase â†’</a>`;document.body.append(footer);
  document.querySelectorAll('.refresh-tool button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.refresh-result').textContent=`Start with ${button.textContent.toLowerCase()}, then use the visit page to confirm the current details.`;}));
})();
